# Generated by Django 5.2.1 on 2025-05-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sharenotes',
            fields=[
                ('docid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('decription', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
